const courses = [
  "A Detailed Guide to the OWASP Top 10",
  "AI for Teachers with ChatGPT",
  "AWS Certified Solutions Architect Associate (SAA-C03)",
  "Adobe Firefly – Start Building and Delivering in Under 30 Minutes",
  "Adobe Premiere Pro CC: Learn Video Editing in Premiere Pro",
  "Advanced 3D Printing with Fusion 360 - Design Your Phone Case",
  "Advanced Data Mining projects with R",
  "Alteryx Advanced",
  "Blender Beginner's Bootcamp",
  "Blender to Unreal Engine - Become a Dungeon Prop Artist",
  "Blender to Unreal Engine 5 The Complete Beginners Guide",
  "Build and Learn ASP.NET 6.0 Blazor Hands-On",
  "Building Games with Scratch 2.0",
  "Building Interactive Dashboards with Tableau",
  "Building a ChatGPT AI with JavaScript - An OpenAI Code-Along Guide",
  "Building a RepRap 3D Printer",
  "Building a Responsive Application with Bootstrap",
  "Building a Search Server with Elasticsearch",
  "CISSP Crash Course",
  "COBIT 2019 Foundation",
  "Certified Associate in Project Management (CAPM)",
  "Certified Ethical Hacker (CEH) v.12",
  "ChatGPT Voice-Powered Chatbot Build with React and FastAPI",
  "ChatGPT and DALL-E: Sell Your Creative Thinking with AI",
  "ChatGPT for Teachers in Education",
  "Chatbots Development with Amazon Lex",
  "Cisco CCNP Data Center DCCOR (350-601)",
  "Cisco CCNP Enterprise ENARSI (300-410)",
  "Cisco CCNP Security SCOR (Exam 350-701)",
  "Cisco CCNP Security SNCF (Exam 300-710)",
  "Cisco CCT Routing and Switching (100-490)",
  "CompTIA A+ Certification Core 2 (220-1102)",
  "CompTIA CySA+ (CS0-003)",
  "CompTIA Linux+ (XK0-005)",
  "Complete SAS Programming Guide - Learn SAS and Become a Data Ninja",
  "Concurrent and Parallel Programming in Python",
  "Create Your First DApp on Ethereum - A Concise Tutorial",
  "Cybersecurity Architecture Fundamentals",
  "Data Analytics in Excel Using Real-World Examples",
  "Deep Learning - Convolutional Neural Networks with TensorFlow",
  "Deep Learning - Crash Course 2023",
  "Deploying AngularJS",
  "DevOps for Web Developers",
  "Elasticsearch 5.x Solutions - Node and Cluster Management",
  "Full Stack Web Development Mastery Course - Novice to Expert",
  "Fundamentals Of Object-Oriented Programming: Java and IntelliJ",
  "Getting Started with jQuery 3",
  "Git and GitHub Masterclass – Fast-Track Your Journey to Git",
  "HashiCorp Certified - Consul Associate Course",
  "How to Use ChatGPT and Generative AI to Help Create Content",
];

const results = [
  {
    name: "AR/VR",
    correct_answers: 1,
    num_questions: 10,
  },
  {
    name: "History of Technology - Hardware",
    correct_answers: 1,
    num_questions: 10,
  },
  {
    name: "Climate Technology",
    correct_answers: 2,
    num_questions: 10,
  },
  {
    name: "Artificial Intelligence (AI)",
    correct_answers: 3,
    num_questions: 10,
  },
  {
    name: "History of Technology - Software",
    correct_answers: 3,
    num_questions: 10,
  },
  {
    name: "Multimodal Models (MM)",
    correct_answers: 3,
    num_questions: 10,
  },
  {
    name: "Web3",
    correct_answers: 3,
    num_questions: 10,
  },
  {
    name: "Blockchain",
    correct_answers: 4,
    num_questions: 10,
  },
  {
    name: "Generative Artificial Intelligence (GAI)",
    correct_answers: 5,
    num_questions: 10,
  },
  {
    name: "Large Language Models (LLMs)",
    correct_answers: 5,
    num_questions: 10,
  },
  {
    name: "Robotics",
    correct_answers: 5,
    num_questions: 10,
  },
  {
    name: "Causal AI (CAI)",
    correct_answers: 6,
    num_questions: 10,
  },
];

module.exports = {
  courses,
  results,
};
